embeddings {
  tensor_name: "agency:00630"
  metadata_path: "00630/agency/metadata.tsv"
  tensor_path: "00630/agency/tensors.tsv"
}
embeddings {
  tensor_name: "sku:00630"
  metadata_path: "00630/sku/metadata.tsv"
  tensor_path: "00630/sku/tensors.tsv"
}
embeddings {
  tensor_name: "special_days:00630"
  metadata_path: "00630/special_days/metadata.tsv"
  tensor_path: "00630/special_days/tensors.tsv"
}
embeddings {
  tensor_name: "month:00630"
  metadata_path: "00630/month/metadata.tsv"
  tensor_path: "00630/month/tensors.tsv"
}
